name: Deploy Project
on: push
jobs:
    test:
        runs-on: ubuntu-latest
        steps: 
        - name: test1
          run: echo "test"
    deploy:
        needs: test
        runs-on: ubuntu-latest
        steps:
        - name: deploy1
          run: echo "deploy" 

        